### ISSUE TITLE
Play Store custom store listing url is not working

### ISSUE THREAD

**Issue by JayMehta97** [BranchMetrics/android-branch-deep-linking-attribution#1039]
### Describe the bug

We have created a custom store listing for our app on Plat Store and the url for that has just an additional `listing` attribute. We tried assigning this url to the branch object using `$android_url` attribute as well as directly updating on the dasboard. It works fine when opened from desktop browser, it redirects to correct custom store listing page but when clicked from an android device it takes to the default store listing instead of the custom store listing.

Default Play store listing url - https://play.google.com/store/apps/details?id=com.example.app
Custom Play store listing url - https://play.google.com/store/apps/details?id=com.example.app&listing=chat

### Steps to reproduce

1. Create a branch deeplink with attribute `$android_url` set for a custom store listing url.
2. Open that branch link on an android device which does not have the app installed.

### Expected behavior

It should open custom store listing page in Play Store.

### SDK Version

5.0.13

### Make and Model

Pixel 6, Vivo V series

### OS

11 and 12

**Comment by jf-branch** [comment]
Hey @JayMehta97! 

We are aware of this. The reason this is occurring is because we actually use the market:// uri scheme to open up the Android Play Store rather than the play.google.com/store. Funny enough it works on some devices and browsers but not others. We are looking into it this quarter and when we make the update to support, I will notify this thread.

**Comment by jf-branch** [comment]
Hey @JayMehta97, 

While we are working on official support for this, a fellow team member mentioned that you can use the market.android.com url instead of the play.google.com url, since market.android.com url redirects to play.google.com, that extra step will prevent us from firing the market:// uri. 

i.e Custom Play store listing url - https://play.google.com/store/apps/details?id=com.example.app&listing=chat ---> Custom Play store listing url - https://market.android.com/details?id=com.example.app&listing=chat
