### ISSUE TITLE
Exposed BRANCH API KEY

### ISSUE THREAD

**Issue by rajasekaranmr** [BranchMetrics/android-branch-deep-linking-attribution#1134]
### Describe the bug

We have a security vulnerability issue with the app because shared preferences are not encrypted in the SDK, and they hold the API key value. As a result, anyone can obtain the API key from the APK through reverse engineering.

### Steps to reproduce

1. Build an Android app with Branch IO configuration.
2. Open the device explorer and navigate to the folder of the app (using the application ID).
3. Open the shared preference file from the folder, and you will see the API key stored with encryption.

### Expected behavior

We need to safeguard our keys to prevent unauthorized reverse engineering.

### SDK Version

5.7.1

### Make and Model

Google Pixel 7

### OS

13

**Comment by echo-branch** [comment]
@rajasekaranmr 
Thanks for reaching out. Please contact our security team at [security@branch.io](mailto:security@branch.io) with any security related questions or concerns. 

One clarifying note about the Branch key is that it is not an encryption key, but rather a type of App ID. So like a username rather than password. Since this topic usually leads into related questions about app validation, user authentication and fraud analysis I recommend getting in touch to go over all the questions your team may have.
