### ISSUE TITLE
Xml design is not good

### ISSUE THREAD

**Issue by mujeeb272** [BranchMetrics/android-branch-deep-linking-attribution#710]
how to edit xml?

**Comment by csalmi-branch** [comment]
@mujeeb272 Could you provide some more details on what issue you are encountering? Do you just need help with editing XML? Or a particular file? What version of the SDK, Android, etc. are you using? I'm not really sure what help we can provide you at this time.

**Comment by mujeeb272** [comment]
Sharing to social platform,that design is not good

**Comment by csalmi-branch** [comment]
Is there something in particular that you do not like about the design or blocked somehow? What exactly is the issue you are encountering?

**Comment by mujeeb272** [comment]
See sharing part design, that design dint like by our client side

**Comment by csalmi-branch** [comment]
What about the design is not liked by your client side? Is it impacting your integration or usage of the SDK? If so, could you provide details of the impact?

As I've stated before, any details you can provide will help us understand what issue you are facing. Otherwise we can't tell whether you are reporting a bug, blocked on integration or usage of a feature, or have a suggested improvement. You are also welcome to submit a pull request if you have a suggested improvement for the SDK.

**Comment by mujeeb272** [comment]
How to integrate xml of dat??

**Comment by mujeeb272** [comment]
Only design improvement is need..and font

**Comment by csalmi-branch** [comment]
Are you asking how to implement sharing? Or how to edit xml configurations?

Can you please provide an example of what your config files look like? Also provide the version of SDK you are using.

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
