### ISSUE TITLE
Initiating Branch integration verification fails on step 6

### ISSUE THREAD

**Issue by jonneymendoza** [BranchMetrics/android-branch-deep-linking-attribution#727]
Hi i am getting the error below:

```
 6. Verifying intent for receiving URI scheme. ... 
g D/BranchSDK_Doctor: ** ERROR ** : Uri scheme 'myApp://' specified in Branch dashboard doesn't match with the deep link intent in manifest file
```

Here is a snippet of my manifest

```
<activity
            android:name=".ui.MainActivity"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">

   <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <data android:scheme="myApp" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

</activity>
```

Am i missing something here?

i tried adding a another data attribute below 

```  
<data
                    android:host="branchCustomLink-app.link/"
                    android:path="/hello"
                    android:scheme="myApp://" />```
```
But no joy?

Link settings in the branch dashboard has the android URI scheme for android set to myApp and i am using version 3.2.0

**Comment by csalmi-branch** [comment]
@jonneymendoza, it seems like you have likely already found this page, but please take a look here and see if this helps with any of your issues.

https://docs.branch.io/apps/android/#troubleshoot-issues

If that doesn't help, can you double check that you have the matching prod (or test) key in your app as in the dashboard?

**Comment by echo-branch** [comment]
closing due to no response from reporter.

**Comment by developer-dmp** [comment]
Hi - I believe I might have a reason as to why this happened. I ran into the same issue and was getting quite frustrated when the SDK_Doctor kept failing me at this step.  What seemed to be the issue for me was how I was declaring the `data` attribute within the intent filter.  I had this in my Manifest:

`<data android:scheme="@string/custom_uri_scheme" />`

Since I need to support having different URI schemes for Production and Staging builds.  I have this resource defined in my `strings.xml` file because I need to reference this string as a delimiter in other areas of my app when performing deep links/converting schemes to "normal" links my app knows how to deep link with.  Putting this value in the manifest placeholders in the `build.gradle` file make it difficult/impossible to get the string value at run time.

After stepping through the code in your `ApkParser.java` file, the `attrValue` field (on line 126 running `io.branch.sdk.android:library:5.0.6`) is set to "resourceID 0x7f11..." meaning I think you don't support actually parsing the value of `@string/custom_uri_scheme` to resolve the string.  If I take the string value that is set in the `strings.xml` file and paste it in the intent filter, the code works fine and my app passes the check.  Hope this helps and would be willing to open a new issue with this!
