### ISSUE TITLE
referringParams is not correct when app is in the background or when app is not open

### ISSUE THREAD

**Issue by andrewcmc** [BranchMetrics/android-branch-deep-linking-attribution#954]
Branch version: 5.0.15
android-sdk-ui:16.0.0

When app is in the background state or app is not open, the referringParams is not correct.
App receive notification at that moment, it shows as below:

`referringParams = {"+clicked_branch_link":false,"+is_first_session":false}`

And then we can not navigate to the specific screen.

It works well when app is in the foreground state.

**Comment by andrewcmc** [comment]
When app in the background or app is not open, there is a related log as below:

`initializing session on user's behalf (onActivityResumed called but SESSION_STATE = UNINITIALISED)`

**Comment by levyschiavetti** [comment]
Right now I have the exact same problem. 
Followed the documentation from top to bottom and sometimes params are empty.

**Comment by AlexZvonik** [comment]
Same happens to me

**Comment by levyschiavetti** [comment]
In my case, setting expectDelayedSessionInitialization to true prior to initializing the instance solved the issue:

```
private fun setupBranch() {
        Branch.enableLogging()
        Branch.expectDelayedSessionInitialization(true)
        Branch.getAutoInstance(this)
    }
```

**Comment by lucamtudor** [comment]
@levyschiavetti thanks for the suggestion!

**Comment by arsalanfakhar** [comment]
> In my case, this was happening when opening the app from a push notification (cold start). I've noticed that, under this circumstance, Branch SDK was doing the POST request twice (I figured one by the lib and another one from the initSession call in activity's onStart). This may cause a confusion concerning which params gets delivered first, causing the inconsistent behavior.
> 
> So, In my case, setting expectDelayedSessionInitialization to true prior to initializing the instance solved the issue, cause then Branch waits for user to initialize the session:
> 
> For cold start:
> 
> ```
> private fun setupBranch() {
>         Branch.enableLogging()
>         Branch.expectDelayedSessionInitialization(true)
>         Branch.getAutoInstance(this)
>     }
> ```
> 
> And since Branch SDK seems to reset this value during initialization, it's necessary to call it again when app goes to background, in order to cover the app running in the background scenario:
> 
> ```
> override fun onPause() {
>         super.onPause()
>         Branch.expectDelayedSessionInitialization(true)
>     }
> ```
> 
> After doing that, no more empty params again.

It worked perfectly after spending two days on the issue without any solution this was very helpful @levyschiavetti

**Comment by pd90** [comment]
> Branch version: 5.0.15 android-sdk-ui:16.0.0
> 
> When app is in the background state or app is not open, the referringParams is not correct. App receive notification at that moment, it shows as below:
> 
> `referringParams = {"+clicked_branch_link":false,"+is_first_session":false}`
> 
> And then we can not navigate to the specific screen.
> 
> It works well when app is in the foreground state.

Currently I am also facing the same issue with branch and Airship integration, have tried various solutions but nothing seems to work

**Comment by jf-branch** [comment]
@pd90, I'm assuming with Airship this is in regards to push notifications correct? If so, could you confirm you are properly adding the branch link as custom data to the push payload for the key"branch" and not utilizing the branch link as the action url of the push payload?

**Comment by pundirAbhishek** [comment]
I am facing a similar kind of issue. 
When i initialized the branch session and then put the app in background and then from recents brought the app to foreground, then the branch is returning `referringParams = {"+clicked_branch_link":false,"+is_first_session":false}`. 
So in that case i don't know where to redirect the user. 
Does anyone have a solution to this?

**Comment by murchant** [comment]
OK, I was facing this issue for months with Airship integration and I finally found a working solution.
This callout on the [Branch documentation](https://help.branch.io/developers-hub/docs/android-advanced-features#section-handle-links-in-your-own-app%20%20*/) was a huge help. 

<img width="878" alt="Screenshot 2023-07-31 at 13 30 03" src="https://github.com/BranchMetrics/android-branch-deep-linking-attribution/assets/17220329/2058c158-7a9e-40ad-8dff-eb1cb9fc3093">

The issue was I was initialising Branch SDK in both places, ActivityA and ActivityB. When I handled the airship deeplink (from a cold start) I was calling both initialising both Activity's. 

As their doc says you need to call `reinit` instead `init` for the Branch session builder when _"linking to the currently open activity or an activity that's in the backstack and partially visible, must be handled via sessionBuilder()....reInit()."_
 
Once I changed this in Activity B the referring params started to be populated. The only thing is they we're marked with `+non_branch_link`. So I needed to parse these deeplinks differently to how I had been
